export const APPRoutes = {
  LOGIN: "/login",
  REGISTER: "/register",
  HOME: "/",
  ABOUT: "/about",
  SERVICES: "/services",
  MENU: "/menu",
  RESERVATION: "/reservation",
  TESTIMONIAL: "/testimonial",
  CONTACT: "/contact",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  SEARCH: "/search",
  DASHBOARD_MENU: "/dashboard/menu",
  DASHBOARD_RESERVATION: "/dashboard/reservation",
  DASHBOARD_RESERVATION_DETAIL: "/dashboard/reservation/detail",
  DASHBOARD_RESERVATION_DETAIL_EDIT: "/dashboard/reservation/detail/edit",
  DASHBOARD_RESERVATION_DETAIL_ADD: "/dashboard/reservation/detail/add",
  DASHBOARD_RESERVATION_DETAIL_DELETE:
    "/dashboard/reservation/detail/delete",
}